[workspace]
members = [
    "crates/consensus",
    "crates/evaluate",
    "crates/monitor",
    "crates/protocol",
    "crates/with-rocksdb",
    "crates/server",
    "crates/alltest"
]
resolver = "2"

[profile.release]
lto = "fat"
strip = "debuginfo"
